---
layout: post
title:  "项目问题"
category: dev
---

## 服务重启
原因：在读写文件时抛出异常，异常未能捕获，于是服务终止然后重启

```
await new Promise(function (resolve, reject) {
    try {
        fs.createReadStream(filePath).pipe(unzip.Extract({ path: dirPath })).on('close', resolve);
    } catch (e) {
        reject(e);
    }
});
```
上面代码的try、catch不能捕获文件操作的异常，所以会引起服务重启。改成如下形势：
```
fs.createReadStream(filePath)
    .pipe(unzip.Extract({path: dirPath}))
    .on('close', resolve)
    .on('error', err => {
        console.log('unzip.complexReportFile.error', err);
        reject(err);
    });
```
